ROYFORD_KE DATA DEALSğŸ”¥HATA NA OKOA YA MITA DATA BADO INAKAM
Instant Delivery-Within seconds!!! 
Till 6ï¸âƒ£3ï¸âƒ£1ï¸âƒ£1ï¸âƒ£7ï¸âƒ£1ï¸âƒ£9ï¸âƒ£
1 purchase per number per day 
ğŸ”¥:Sh55=1.25GB TILL MIDNIGHT 
ğŸ”¥:Sh20=250MBs,,24HRS
ğŸ”¥:Sh19=1Gb Valid 1hr
ğŸ”¥:Sh50=1.5GB valid 3hrs
ğŸ”¥:Sh99=1GB valid 24hrs
ğŸ”¥:Sh49=350MBs valid for 7days

PAY TO TILL :6ï¸âƒ£3ï¸âƒ£1ï¸âƒ£1ï¸âƒ£7ï¸âƒ£1ï¸âƒ£9ï¸âƒ£

ONLY THESE PACKAGES ARE AVAILABLE FOR MULTIPLE PURCHASE
ğŸ”¥ Ksh 22=1GB valid 1hr
ğŸ”¥Kshs 52=1.5GB valid 3hrs
ğŸ”¥Ksh 110=2GB valid 24hrs

MINUTES WITH/WITHOUT OKOA 
â¤ï¸Kshs 23-45mins valid 3hrs
â¤ï¸Kshs 51-50minutes valid midnight 
â¤ï¸Kshs 101-100 minutes valid 48hrs

âœ‰ SMS BUNDLES WITH OR WITHOUT OKOA

ğŸ“Œ 1000 SMS (Weekly) â€“ Ksh 30

ğŸ“Œ 200 SMS (Daily) â€“ Ksh 10

ğŸ“Œ 20 SMS (Daily) â€“ Ksh 5

ğŸ’³ HOW TO PAY

Till Number: 6ï¸âƒ£3ï¸âƒ£1ï¸âƒ£1ï¸âƒ£7ï¸âƒ£1ï¸âƒ£9ï¸âƒ£

The bundles will be auto-loaded to the number used in making payment ğŸ‘Œ
